[config]
schemaVersion = "0.0.1"

[package]
namespace = "notTamion"
name = "InfoSkull"
versionNumber = "2.0.0"
description = "White Knuckle mod that aims to make UI more customizable"
websiteUrl = "https://github.com/notTamion/InfoSkull"
containsNsfwContent = false
[package.dependencies]


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""


[publish]
repository = "https://thunderstore.dev"
communities = [ "white-knuckle" ]
[publish.categories]
white-knuckle = [ "leaderboard-legal", "mods", "tools", "misc", "libraries", "tweaks" ]


