name: Publish

on:
  push:
    branches:
      - main
      - dev
      - v2 # REMOVE ON MERGE

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bins SSH KEY
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.BINS_REPO_KEY }}
      - name: Checkout Bins
        run: |
          git clone git@github.com:nottamion/white-knuckle-bins.git libs
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Build and Package
        run: |
          dotnet build -c Release
          mkdir rel 
          mv ./bin/Release/net471/InfoSkull.dll ./rel
      - name: Determine Thunderstore Environment
        id: tstore-env
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "token=${{ secrets.THUNDERSTORE_TOKEN }}" >> $GITHUB_OUTPUT
            echo "repo=https://thunderstore.io" >> $GITHUB_OUTPUT
          else
            echo "token=${{ secrets.THUNDERSTORE_TOKEN_DEV }}" >> $GITHUB_OUTPUT
            echo "repo=https://thunderstore.dev" >> $GITHUB_OUTPUT
          fi 
      - name: Publish to Thunderstore
        run: |
          sed -i '1s/^\xEF\xBB\xBF//' README.md
          dotnet tool install -g tcli
          tcli publish \
            --token "${{ steps.tstore-env.outputs.token }}" \
            --repository "${{ steps.tstore-env.outputs.repo }}"